// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_lXTMckEhB426ax37YgjQmOxsjLe7q_s',
    appId: '1:216798493473:web:d642ad026aaa4cfa24dc60',
    messagingSenderId: '216798493473',
    projectId: 'swapstash-49199',
    authDomain: 'swapstash-49199.firebaseapp.com',
    storageBucket: 'swapstash-49199.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLxUvuziB2vsl-nzncQBKAqCJGCM9asHo',
    appId: '1:216798493473:android:09b94621330a7da624dc60',
    messagingSenderId: '216798493473',
    projectId: 'swapstash-49199',
    storageBucket: 'swapstash-49199.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG9tnhkuM3HJfOHiPYTsKteif-XUkzKcE',
    appId: '1:216798493473:ios:62e9df6e2933e75924dc60',
    messagingSenderId: '216798493473',
    projectId: 'swapstash-49199',
    storageBucket: 'swapstash-49199.firebasestorage.app',
    iosBundleId: 'com.example.swapstash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG9tnhkuM3HJfOHiPYTsKteif-XUkzKcE',
    appId: '1:216798493473:ios:62e9df6e2933e75924dc60',
    messagingSenderId: '216798493473',
    projectId: 'swapstash-49199',
    storageBucket: 'swapstash-49199.firebasestorage.app',
    iosBundleId: 'com.example.swapstash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_lXTMckEhB426ax37YgjQmOxsjLe7q_s',
    appId: '1:216798493473:web:f0defb74dfddff8724dc60',
    messagingSenderId: '216798493473',
    projectId: 'swapstash-49199',
    authDomain: 'swapstash-49199.firebaseapp.com',
    storageBucket: 'swapstash-49199.firebasestorage.app',
  );
}
